name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create ssh dir
        run: mkdir -p ~/.ssh
      - name: Copy ssh public key 
        run: echo "${{env.SSH_PUB}}" > ~/.ssh/id_rsa.pub
      - name: Change mode
        run: chmod 600 ~/.ssh/id_rsa.pub
      - name: SSH
        shell: bash
        run: ssh -tt root@softrize.com
#      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
#      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#      - name: Check out repository code
#        uses: actions/checkout@v3
